import type { Branch } from "@/lib/types";

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 1,
    name: "Muscle Gym, Bagambur",
    address: "1st Floor, Vaigai Complex, Near Rasi Petrol Bunk, K.Paraipatti, Begampur, Dindigul-624002",
    phone: ["9944579994"],
    coordinates: { lat: 10.3541, lng: 77.9622 },
    contactNumber: "9944579994",
    hours: { weekdays: "05:30 AM - 09:00 PM", sunday: "05:30 AM - 10:00 AM", womens: "10:00 AM - 04:00 PM" },
    amenities: ["Premium Imported Equipment", "Dressing Room", "Shower", "Supplements Store", "Personal Training"],
    rating: "4.4",
    reviews: 64,
    mapUrl: "https://maps.app.goo.gl/HV6E7iYSwSvarJks8",
  },
  {
    id: 2,
    name: "Muscle Fitness Studio Unisex, Trichy Road",
    address: "Sakthi Complex, D-Mart Opposite, Trichy Bypass Service Road, Dindigul",
    phone: ["9787045050", "9944579994"],
    coordinates: { lat: 10.3789, lng: 77.9954 },
    contactNumber: "9787045050",
    hours: { weekdays: "05:30 AM - 09:00 PM", sunday: "05:30 AM - 10:00 AM" },
    amenities: ["Advanced Lifting Platforms", "Dressing Room", "Shower", "Supplements Store", "Personal Training", "Cardio Zone"],
    rating: "5.0",
    reviews: 62,
    mapUrl: "https://maps.app.goo.gl/HTMCjtaGLJ318Mcj8",
  },
  {
    id: 3,
    name: "Muscle Pro Fitness Studio Unisex, Palani Road",
    address: "St Joseph Furniture Building, 1st Floor, Opposite Income Tax Office, Palani Road, Dindigul",
    phone: ["9600578808", "9944579994"],
    coordinates: { lat: 10.3668, lng: 77.9515 },
    contactNumber: "9600578808",
    hours: { weekdays: "05:30 AM - 09:00 PM", sunday: "05:30 AM - 10:00 AM" },
    amenities: ["AC Gym Floor", "Imported Equipment", "Dressing Room", "Shower", "Steam Room", "Supplements Store", "Personal Training", "Unisex Training Areas"],
    rating: "5.0",
    reviews: 10,
    mapUrl: "https://maps.app.goo.gl/nFLFXdBfA94XheWU8",
  },
];


export const INITIAL_TRAINERS = [
  {
    id: 1,
    name: "Master RAJKUMAR",
    specialty: "Head Coach / General Secretary - Dindigul District Gym Owner's Association",
    experience: 18,
    bio: "With over 18 years of professional fitness training experience, Master Rajkumar has trained and transformed thousands of individuals in Dindigul. He specializes in competition-level bodybuilding coaching, powerlifting, strength conditioning, and lifestyle transformations.",
    imageUrl: "/trainers/rajkumar.jpg",
    certifications: "Certified Advanced Personal Trainer, Nutrition & Dietetics Specialist",
    branch: "All Branches",
    socialLinks: { instagram: "https://instagram.com/muscle_gym_dindigul", facebook: "#" },
  },
  {
    id: 2,
    name: "Rajesh Kumar",
    specialty: "Cardio & High-Intensity Interval Training (HIIT) Coach",
    experience: 6,
    bio: "Rajesh is a passionate coach who specializes in cardiovascular endurance, fat loss programs, and metabolic conditioning. He designs engaging high-energy sessions that burn fat and build stamina.",
    imageUrl: "/trainers/coach1.jpg",
    certifications: "Certified Group Fitness Instructor, CPR & First Aid Certified",
    branch: "Muscle Fitness Studio Unisex, Trichy Road",
    socialLinks: { instagram: "https://instagram.com/muscle_gym_dindigul", facebook: "#" },
  },
  {
    id: 3,
    name: "Priya Sharma",
    specialty: "Weight Loss & Functional Movement Specialist",
    experience: 5,
    bio: "Priya focuses on corrective exercises, functional movement, and targeted fat loss plans. She is dedicated to helping members build core strength and improve flexibility for everyday health.",
    imageUrl: "/trainers/coach3.jpg",
    certifications: "Certified Fitness Trainer (ISSA), Specialization in Female Fitness",
    branch: "Muscle Pro Fitness Studio Unisex, Palani Road",
    socialLinks: { instagram: "https://instagram.com/muscle_gym_dindigul", facebook: "#" },
  },
  {
    id: 4,
    name: "Selvam",
    specialty: "Strength & Conditioning Specialist",
    experience: 4,
    bio: "Selvam specializes in weight training, muscle hypertrophy, and personalized competition preparation. He focuses on safety, proper biomechanics, and consistent progress tracking.",
    imageUrl: "/trainers/coach4.jpg",
    certifications: "Certified Fitness Instructor, Specialized in Muscle Hypertrophy",
    branch: "Muscle Gym, Bagambur",
    socialLinks: { instagram: "https://instagram.com/muscle_gym_dindigul", facebook: "#" },
  },
];

export const INITIAL_PROGRAMS = [
  {
    id: 1,
    title: "Muscle Gain & Hypertrophy",
    description: "Tailored weight training protocols, progressive overload tracking, and nutrition coaching to build solid muscle mass.",
    category: "Strength",
    schedule: "Mon - Sat (Any timing)",
    icon: "Dumbbell",
  },
  {
    id: 2,
    title: "Weight Loss & Fat Burn",
    description: "High-intensity metabolic workouts combined with personalized calorie deficit meal plans to melt away fat and tone your physique.",
    category: "Cardio & Fitness",
    schedule: "Mon - Sat (Morning/Evening)",
    icon: "Flame",
  },
  {
    id: 3,
    title: "Powerlifting & Strength Conditioning",
    description: "Focus on squats, bench press, and deadlifts under Master Rajkumar's expert guidance. Build absolute strength.",
    category: "Athletic",
    schedule: "Tue, Thu, Sat (Special batches)",
    icon: "ShieldAlert",
  },
  {
    id: 4,
    title: "Personal Training",
    description: "1-on-1 private coaching with specialized attention, customized nutrition guides, and daily progress reviews.",
    category: "Coaching",
    schedule: "Flexible booking",
    icon: "UserCheck",
  },
  {
    id: 5,
    title: "Cardio & Endurance",
    description: "Use of advanced imported treadmills, cross-trainers, and spin bikes to optimize cardiovascular fitness and heart health.",
    category: "Cardio",
    schedule: "Daily access",
    icon: "HeartPulse",
  },
  {
    id: 6,
    title: "Functional & Core Training",
    description: "Kettlebell, battle ropes, and bodyweight exercises to build functional athleticism, core stability, and balance.",
    category: "Functional",
    schedule: "Mon, Wed, Fri",
    icon: "Activity",
  },
];

export const INITIAL_TESTIMONIALS = [
  {
    id: 1,
    name: "Dinesh",
    quote: "Muscle Gym changed my life. Under Master Rajkumar's personal guidance, I dropped from 115 kg to 96 kg in just 45 days! The equipment is premium and the atmosphere is pure motivation.",
    rating: 5,
    imageUrl: "/images/testimonials/arun.jpg",
    goal: "Weight Loss & Toning",
    result: "-19 kg in 45 days",
  },
  {
    id: 2,
    name: "Karthikeyan",
    quote: "Best gym in Dindigul, hands down. I train at the Trichy Bypass branch. It's spacious, fully AC, and the imported machines are smooth. Master Rajkumar's powerlifting tips helped me add 40kg to my deadlift!",
    rating: 5,
    imageUrl: "/images/testimonials/karthi.jpg",
    goal: "Powerlifting & Strength",
    result: "+40kg deadlift max",
  },
  {
    id: 3,
    name: "Sanmugapriya",
    quote: "As a beginner, I was nervous about starting strength training, but trainer Priya made me feel comfortable. I went from 97 kg to 91 kg in just 1 month. The unisex training atmosphere is very safe and clean.",
    rating: 5,
    imageUrl: "/images/testimonials/meera.jpg",
    goal: "General Fitness & Core Strength",
    result: "-6 kg in 1 month",
  },
];
